# Optional Lab - Softmax Function
In this lab, we will explore the softmax function. This function is used in both Softmax Regression and in Neural Networks when solving Multiclass Classification problems.  

<center>  <img  src="./images/C2_W2_Softmax_Header.PNG" width="600" />  <center/>

  

In [1]:
import numpy as np
import matplotlib.pyplot as plt
plt.style.use('./deeplearning.mplstyle')
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from IPython.display import display, Markdown, Latex
from sklearn.datasets import make_blobs
%matplotlib widget
from matplotlib.widgets import Slider
from lab_utils_common import dlc
from lab_utils_softmax import plt_softmax
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

2023-05-03 17:12:35.007463: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


> **Note**: Normally, in this course, the notebooks use the convention of starting counts with 0 and ending with N-1,  $\sum_{i=0}^{N-1}$, while lectures start with 1 and end with N,  $\sum_{i=1}^{N}$. This is because code will typically start iteration with 0 while in lecture, counting 1 to N leads to cleaner, more succinct equations. This notebook has more equations than is typical for a lab and thus  will break with the convention and will count 1 to N.

## Softmax Function
In both softmax regression and neural networks with Softmax outputs, N outputs are generated and one output is selected as the predicted category. In both cases a vector $\mathbf{z}$ is generated by a linear function which is applied to a softmax function. The softmax function converts $\mathbf{z}$  into a probability distribution as described below. After applying softmax, each output will be between 0 and 1 and the outputs will add to 1, so that they can be interpreted as probabilities. The larger inputs  will correspond to larger output probabilities.
<center>  <img  src="./images/C2_W2_SoftmaxReg_NN.png" width="600" />  

The softmax function can be written:
$$a_j = \frac{e^{z_j}}{ \sum_{k=1}^{N}{e^{z_k} }} \tag{1}$$
The output $\mathbf{a}$ is a vector of length N, so for softmax regression, you could also write:
\begin{align}
\mathbf{a}(x) =
\begin{bmatrix}
P(y = 1 | \mathbf{x}; \mathbf{w},b) \\
\vdots \\
P(y = N | \mathbf{x}; \mathbf{w},b)
\end{bmatrix}
=
\frac{1}{ \sum_{k=1}^{N}{e^{z_k} }}
\begin{bmatrix}
e^{z_1} \\
\vdots \\
e^{z_{N}} \\
\end{bmatrix} \tag{2}
\end{align}
    

Which shows the output is a vector of probabilities. The first entry is the probability the input is the first category given the input $\mathbf{x}$ and parameters $\mathbf{w}$ and $\mathbf{b}$.  
Let's create a NumPy implementation:

In [2]:
def my_softmax(z):
    ez = np.exp(z)
    sm = ez/np.sum(ez)
    return sm

* the exponential in the numerator of the softmax magnifies small differences in the values 
* the output values sum to one
* the softmax spans all of the outputs. A change in `z0` for example will change the values of `a0`-`a3`. Compare this to other activations such as ReLU or Sigmoid which have a single input and single output.

## Cost
<center> <img  src="./images/C2_W2_SoftMaxCost.png" width="400" />    <center/>

The loss function associated with Softmax, the cross-entropy loss, is:
\begin{equation}
  L(\mathbf{a},y)=\begin{cases}
    -log(a_1), & \text{if $y=1$}.\\
        &\vdots\\
     -log(a_N), & \text{if $y=N$}
  \end{cases} \tag{3}
\end{equation}

Where y is the target category for this example and $\mathbf{a}$ is the output of a softmax function. In particular, the values in $\mathbf{a}$ are probabilities that sum to one.
>**Recall:** In this course, Loss is for one example while Cost covers all examples. 
 
 
Note in (3) above, only the line that corresponds to the target contributes to the loss, other lines are zero. To write the cost equation we need an 'indicator function' that will be 1 when the index matches the target and zero otherwise. 
    $$\mathbf{1}\{y == n\} = =\begin{cases}
    1, & \text{if $y==n$}.\\
    0, & \text{otherwise}.
  \end{cases}$$
Now the cost is:
\begin{align}
J(\mathbf{w},b) = -\frac{1}{m} \left[ \sum_{i=1}^{m} \sum_{j=1}^{N}  1\left\{y^{(i)} == j\right\} \log \frac{e^{z^{(i)}_j}}{\sum_{k=1}^N e^{z^{(i)}_k} }\right] \tag{4}
\end{align}

Where $m$ is the number of examples, $N$ is the number of outputs. This is the average of all the losses.


## Tensorflow
This lab will discuss two ways of implementing the softmax, cross-entropy loss in Tensorflow, the 'obvious' method and the 'preferred' method. The former is the most straightforward while the latter is more numerically stable.

Let's start by creating a dataset to train a multiclass classification model.

In [3]:
# make  dataset for example
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)

### The *Obvious* organization

The model below is implemented with the softmax as an activation in the final Dense layer.
The loss function is separately specified in the `compile` directive. 

The loss function is `SparseCategoricalCrossentropy`. This loss is described in (3) above. In this model, the softmax takes place in the last layer. The loss function takes in the softmax output which is a vector of probabilities. 

In [4]:
model = Sequential(
    [
        Dense(25, activation='relu'),
        Dense(15, activation='relu'),
        Dense(4, activation='softmax') 
    ]
)

model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(),
    optimizer=tf.keras.optimizers.Adam(0.001)
)

model.fit(
    X_train, y_train,
    epochs=10
)

2023-05-03 17:12:37.406723: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


Epoch 1/10
63/63 [==============================] - 0s 719us/step - loss: 0.9593
Epoch 2/10
63/63 [==============================] - 0s 680us/step - loss: 0.4271
Epoch 3/10
63/63 [==============================] - 0s 638us/step - loss: 0.1944
Epoch 4/10
63/63 [==============================] - 0s 645us/step - loss: 0.1069
Epoch 5/10
63/63 [==============================] - 0s 692us/step - loss: 0.0772
Epoch 6/10
63/63 [==============================] - 0s 639us/step - loss: 0.0633
Epoch 7/10
63/63 [==============================] - 0s 655us/step - loss: 0.0555
Epoch 8/10
63/63 [==============================] - 0s 631us/step - loss: 0.0499
Epoch 9/10
63/63 [==============================] - 0s 632us/step - loss: 0.0453
Epoch 10/10
63/63 [==============================] - 0s 642us/step - loss: 0.0419


Because the softmax is integrated into the output layer, the output is a vector of probabilities. 

In [5]:
p_nonpreferred = model.predict(X_train)
print(f'{p_nonpreferred[:2]}')

# what is the range of the probabilities
print("largest value", np.max(p_nonpreferred), "smallest value", np.min(p_nonpreferred))

63/63 [==============================] - 0s 511us/step
[[2.27e-03 9.16e-03 9.71e-01 1.75e-02]
 [9.96e-01 4.07e-03 4.04e-05 5.48e-06]]
largest value 0.99999917 smallest value 1.1823293e-09


### Preferred <img align="Right" src="./images/C2_W2_softmax_accurate.png"  style=" width:400px; padding: 10px 20px ; ">
Recall from lecture, more stable and accurate results can be obtained if the softmax and loss are combined during training.   This is enabled by the 'preferred' organization shown here.


In the preferred organization the final layer has a linear activation. For historical reasons, the outputs in this form are referred to as *logits*. The loss function has an additional argument: `from_logits = True`. This informs the loss function that the softmax operation should be included in the loss calculation. This allows for an optimized implementation.

In [6]:
preferred_model = Sequential(
    [
        Dense(25, activation='relu'),
        Dense(15, activation='relu'),
        Dense(4, activation='linear') 
    ]
)

preferred_model.compile(
    loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=tf.keras.optimizers.Adam(0.001)
)

preferred_model.fit(
    X_train, y_train,
    epochs=10
)

Epoch 1/10
63/63 [==============================] - 0s 731us/step - loss: 0.9490
Epoch 2/10
63/63 [==============================] - 0s 700us/step - loss: 0.3985
Epoch 3/10
63/63 [==============================] - 0s 646us/step - loss: 0.1976
Epoch 4/10
63/63 [==============================] - 0s 633us/step - loss: 0.1178
Epoch 5/10
63/63 [==============================] - 0s 639us/step - loss: 0.0839
Epoch 6/10
63/63 [==============================] - 0s 641us/step - loss: 0.0687
Epoch 7/10
63/63 [==============================] - 0s 645us/step - loss: 0.0604
Epoch 8/10
63/63 [==============================] - 0s 651us/step - loss: 0.0548
Epoch 9/10
63/63 [==============================] - 0s 645us/step - loss: 0.0511
Epoch 10/10
63/63 [==============================] - 0s 655us/step - loss: 0.0475


#### Output Handling
Notice that in the preferred model, the outputs are not probabilities, but can range from large negative numbers to large positive numbers. The output must be sent through a softmax when performing a prediction that expects a probability. 
Let's look at the preferred model outputs:

In [7]:
# output are not probabilities but the z's
p_preferred = preferred_model.predict(X_train)
print(f'{p_preferred[:2]}')

# range of z's?
print("largest value", np.max(p_preferred), "smallest value", np.min(p_preferred))

63/63 [==============================] - 0s 475us/step
[[-2.15 -2.78  5.87  2.45]
 [ 5.47  0.57 -1.88 -4.67]]
largest value 17.17998 smallest value -13.123912


The output predictions are not probabilities!
If the desired output are probabilities, the output should be be processed by a [softmax](https://www.tensorflow.org/api_docs/python/tf/nn/softmax).

In [8]:
# map to softmax
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")

# range of probabilities
print("largest value", np.max(sm_preferred), "smallest value", np.min(sm_preferred))

two example output vectors:
 [[3.19e-04 1.70e-04 9.68e-01 3.19e-02]
 [9.92e-01 7.34e-03 6.38e-04 3.90e-05]]
largest value 0.9999969 smallest value 6.904161e-14


To select the most likely category, the softmax is not required. One can find the index of the largest output using [np.argmax()](https://numpy.org/doc/stable/reference/generated/numpy.argmax.html).

The index of the probabilties correspond to the categories. The therefore the index with the highest z/softmax prob will be the most likely category. 

In [9]:
p_preferred[0]

array([-2.15, -2.78,  5.87,  2.45], dtype=float32)

In [10]:
np.argmax(p_preferred[0])

2

In [11]:
# z's output
for i in range(10):
    print(f'{p_preferred[i]}, category: {np.argmax(p_preferred[i])}')

[-2.15 -2.78  5.87  2.45], category: 2
[ 5.47  0.57 -1.88 -4.67], category: 0
[ 4.08  0.79 -1.59 -3.77], category: 0
[-0.45  3.53 -2.13 -2.09], category: 1
[ 2.24 -4.23  7.85 -1.65], category: 2
[-1.32 -3.69  7.6   1.72], category: 2
[-0.73  4.23 -2.28 -2.57], category: 1
[ 7.8  -1.29 -0.79 -5.57], category: 0
[-0.46  3.9  -2.43 -2.3 ], category: 1
[-7.15 -2.54  3.37  9.42], category: 3


In [12]:
# probabilities output
for i in range(10):
    print(f'{sm_preferred[i]}, category: {np.argmax(sm_preferred[i])}')

[3.19e-04 1.70e-04 9.68e-01 3.19e-02], category: 2
[9.92e-01 7.34e-03 6.38e-04 3.90e-05], category: 0
[9.60e-01 3.60e-02 3.32e-03 3.75e-04], category: 0
[0.02 0.97 0.   0.  ], category: 1
[3.64e-03 5.60e-06 9.96e-01 7.44e-05], category: 2
[1.34e-04 1.24e-05 9.97e-01 2.77e-03], category: 2
[0.01 0.99 0.   0.  ], category: 1
[1.00e+00 1.13e-04 1.86e-04 1.57e-06], category: 0
[0.01 0.98 0.   0.  ], category: 1
[6.39e-08 6.39e-06 2.36e-03 9.98e-01], category: 3


## SparseCategorialCrossentropy or CategoricalCrossEntropy
Tensorflow has two potential formats for target values and the selection of the loss defines which is expected.
- SparseCategorialCrossentropy: expects the target to be an integer corresponding to the index. For example, if there are 10 potential target values, y would be between 0 and 9. 
- CategoricalCrossEntropy: Expects the target value of an example to be one-hot encoded where the value at the target index is 1 while the other N-1 entries are zero. An example with 10 potential target values, where the target is 2 would be [0,0,1,0,0,0,0,0,0,0].
